name: Main CI

on:
  push:
    branches: [ 'ai_main_885320a640e6', 'main' ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node version
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Echo
        run: echo "Main workflow healthy"
